image: python:3.9

before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev
  - gem install dpl

stages:
  - lint
  - test
  - deploy

linting:
  stage: lint
  script:
    - pip install -r requirements.txt
    - pylint *.py 
  allow_fail: true

testing:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest
  allow_fail: true



   
