image: python:3.9

before_script:
  - apt-get update -qy
<<<<<<< HEAD
  - apt-get install -y ruby-dev
=======
>>>>>>> 2c782bfc1737c0e09c55bb667bea4dd631e74c3c
  - apt-get install -y python3-dev
  - gem install dpl

stages:
  - lint
  - test
  - deploy

linting:
  stage: lint
  script:
    - pip install -r requirements.txt
    - pylint *.py 
  allow_failure: true

testing:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest
  allow_failure: true



   
